/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import metier.Adherent;
import metier.Livre;

import metier.AdherentService;
import metier.Emprunt;
import physique.data.ServiceLivreImpl;
import physique.data.ServiceAdherentImpl;
import metier.LivreService;
import physique.data.ServiceEmpruntImpl;
import metier.EmpruntService;
import metier.MetierFactory;
/**
 *
 * @author maxime
 */ 
public class test extends javax.swing.JFrame {
 private Emprunt emprunt;
 private Adherent adherent;
 private Livre livre;
 private ServiceLivreImpl livresrv=new ServiceLivreImpl();
 private ServiceEmpruntImpl empruntsrv= new ServiceEmpruntImpl();
 private List<Adherent> adherentss=new ArrayList<Adherent>();
 private List<Livre> livress=new ArrayList<Livre>();
 private Emprunt dateEmprunt;
 private AdherentService adherentsrv= MetierFactory.getAdherentService();
 /**
     * Creates new form test
     */
    public test() throws Exception {
        initComponents();
     

        adherentss=adherentsrv.getAll();
        for(int i=0; i<adherentss.size(); i++){
            jComboBoxAdherent.addItem(adherentss.get(i));
        }
        livress= livresrv.getAll();
        for(int j=0;j<livress.size();j++){
            jComboBoxLivre.addItem(livress.get(j));
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        Jnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jprenom = new javax.swing.JTextField();
        jAjouter = new javax.swing.JButton();
        jSupprimer = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jAnnuler = new javax.swing.JButton();
        AffTab = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTitre = new javax.swing.JTextField();
        jAuteur = new javax.swing.JTextField();
        jAjouter1 = new javax.swing.JButton();
        jSupprimer1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jAffLivre = new javax.swing.JButton();
        jInternalFrame14 = new javax.swing.JInternalFrame();
        jAjouterEmprunt = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jComboBoxAdherent = new javax.swing.JComboBox();
        jComboBoxLivre = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jAffTab = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setText("Prenom");

        Jnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JnomActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom");

        jAjouter.setText("ajouter");
        jAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAjouterActionPerformed(evt);
            }
        });

        jSupprimer.setText("Supprimer");
        jSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSupprimerActionPerformed(evt);
            }
        });

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Annuler");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jAnnuler.setText("Annuler");
        jAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnnulerActionPerformed(evt);
            }
        });

        AffTab.setText("AffTab");
        AffTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Jnom, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jAjouter)
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AffTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAnnuler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(137, 137, 137)
                        .addComponent(jButton2))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSupprimer)))
                .addGap(353, 353, 353))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(394, 394, 394)
                    .addComponent(jButton4)
                    .addContainerGap(436, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AffTab)
                .addGap(12, 12, 12)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSupprimer)
                    .addComponent(jAjouter)
                    .addComponent(jAnnuler))
                .addGap(60, 60, 60)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jButton4)
                    .addContainerGap(83, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Adherent", jInternalFrame1);

        jLabel3.setText("Titre");

        jLabel4.setText("Auteur");

        JTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTitreActionPerformed(evt);
            }
        });

        jAjouter1.setText("ajouter");
        jAjouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAjouter1ActionPerformed(evt);
            }
        });

        jSupprimer1.setText("Supprimer");
        jSupprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSupprimer1ActionPerformed(evt);
            }
        });

        jButton3.setText("Annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jAffLivre.setText("AffLivre");
        jAffLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAffLivreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAjouter1)
                            .addComponent(JTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jAffLivre)
                        .addComponent(jSupprimer1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(27, 27, 27))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jAjouter1)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSupprimer1)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jAffLivre)
                .addGap(158, 158, 158))
        );

        jTabbedPane1.addTab("Livre", jInternalFrame2);

        jAjouterEmprunt.setText("ajouter");
        jAjouterEmprunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAjouterEmpruntActionPerformed(evt);
            }
        });

        jButton15.setText("Annuler");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jComboBoxAdherent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAdherentActionPerformed(evt);
            }
        });

        jComboBoxLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLivreActionPerformed(evt);
            }
        });

        jLabel5.setText("Liste Adherent");

        jLabel6.setText("Liste Livre");

        jDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateActionPerformed(evt);
            }
        });

        jLabel7.setText("Date");

        jAffTab.setText("AffTab");
        jAffTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAffTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame14Layout = new javax.swing.GroupLayout(jInternalFrame14.getContentPane());
        jInternalFrame14.getContentPane().setLayout(jInternalFrame14Layout);
        jInternalFrame14Layout.setHorizontalGroup(
            jInternalFrame14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame14Layout.createSequentialGroup()
                        .addComponent(jAjouterEmprunt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jInternalFrame14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jInternalFrame14Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(jInternalFrame14Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel7)
                            .addContainerGap()))
                    .addGroup(jInternalFrame14Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAffTab, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jInternalFrame14Layout.setVerticalGroup(
            jInternalFrame14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame14Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jInternalFrame14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame14Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAjouterEmprunt)
                            .addComponent(jButton15)))
                    .addGroup(jInternalFrame14Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jAffTab)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Emprunt", jInternalFrame14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();         // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jSupprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSupprimer1ActionPerformed
        try {
            String titre = this.JTitre.getText();
            String auteur = this.jAuteur.getText();
            this.livre = new Livre(auteur, titre);
            System.out.println(livre);
            this.livresrv.remove(livre);
        } catch (Exception ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }

}//GEN-LAST:event_jSupprimer1ActionPerformed

    private void jAjouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAjouter1ActionPerformed
        try {
            String titre = this.JTitre.getText();
            String auteur = this.jAuteur.getText();
            this.livre = new Livre(auteur, titre);
            System.out.println(livre);
            this.livresrv.add(livre);
        } catch (Exception ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
}//GEN-LAST:event_jAjouter1ActionPerformed

    private void JTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTitreActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_JTitreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSupprimerActionPerformed
 try {
            String nom = this.jprenom.getText();
            String prenom = this.Jnom.getText();
            //try {
            this.adherent = new Adherent(nom, prenom);
            System.out.println(adherent);
            this.adherentsrv.remove(adherent);
            // } catch (Exception ex) {
            //Logger.getLogger(Max.class.getName()).log(Level.SEVERE, null, ex);
            //}
        } catch (Exception ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }



}//GEN-LAST:event_jSupprimerActionPerformed

    private void jAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAjouterActionPerformed
        try {
            String nom = this.jprenom.getText();
            String prenom = this.Jnom.getText();
            //try {
            this.adherent = new Adherent(nom, prenom);
            System.out.println(adherent);
            this.adherentsrv.add(adherent);
            // } catch (Exception ex) {
            //Logger.getLogger(Max.class.getName()).log(Level.SEVERE, null, ex);
            //}
        } catch (Exception ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jAjouterActionPerformed

    private void JnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JnomActionPerformed

}//GEN-LAST:event_JnomActionPerformed

    private void jAjouterEmpruntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAjouterEmpruntActionPerformed
        Adherent adherent= (Adherent) this.jComboBoxAdherent.getSelectedItem();
        Livre livre= (Livre) this.jComboBoxLivre.getSelectedItem();
        String dateEmprunt =  this.jDate.getText();
        /*int i;
        i=Integer.parseInt(dateEmprunt);*/

        this.emprunt = new Emprunt(livre,adherent,dateEmprunt);
        System.out.println(emprunt);
        try {
            this.empruntsrv.add(emprunt);
        } catch (Exception ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
        
    }//GEN-LAST:event_jAjouterEmpruntActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jComboBoxAdherentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAdherentActionPerformed
        
    }//GEN-LAST:event_jComboBoxAdherentActionPerformed

    private void jComboBoxLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLivreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLivreActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AffTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffTabActionPerformed
            // TODO add your handling code here:
        new AnnuaireAdherent().setVisible(true);
    }//GEN-LAST:event_AffTabActionPerformed

    private void jAffLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAffLivreActionPerformed
        new AnnuaireLivre().setVisible(true);        
    }//GEN-LAST:event_jAffLivreActionPerformed

    private void jDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateActionPerformed

    private void jAffTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAffTabActionPerformed
        // TODO add your handling code here:
        new AnnuaireEmprunt().setVisible(true);
    }//GEN-LAST:event_jAffTabActionPerformed

    private void jAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnnulerActionPerformed
    this.dispose();
    }//GEN-LAST:event_jAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new test().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AffTab;
    private javax.swing.JTextField JTitre;
    private javax.swing.JTextField Jnom;
    private javax.swing.JButton jAffLivre;
    private javax.swing.JToggleButton jAffTab;
    private javax.swing.JButton jAjouter;
    private javax.swing.JButton jAjouter1;
    private javax.swing.JButton jAjouterEmprunt;
    private javax.swing.JButton jAnnuler;
    private javax.swing.JTextField jAuteur;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBoxAdherent;
    private javax.swing.JComboBox jComboBoxLivre;
    private javax.swing.JTextField jDate;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame14;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jSupprimer;
    private javax.swing.JButton jSupprimer1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jprenom;
    // End of variables declaration//GEN-END:variables
}
